## 0. Import Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os

from sklearn.preprocessing import OneHotEncoder

## 1. Read Dataset as DataFrame --> "business+economy.csv"

In [2]:
cwd = os.getcwd()

folder_name = "data"

# Dataset contains flight information and prices
file_name = "business+economy.csv"

file_p = os.path.join(cwd, folder_name, file_name)

data = pd.read_csv(file_p)

## 2. Dataset Info & Summary

In [3]:
data.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [5]:
data.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

#### Drop Unrequired Feature Columns

In [6]:
# First column --> Column counting for ticket number
data = data.iloc[:, 1:]

# Column of flight's code --> Not important
data = data.drop('flight', axis=1)

## 3. One-Hot Encoding

In [7]:
categorical_features_label = data.select_dtypes(include=['object']).columns.to_list()

print(categorical_features_label)

['airline', 'source_city', 'departure_time', 'stops', 'arrival_time', 'destination_city', 'class']

In [8]:
encoder = OneHotEncoder(sparse_output=False)

one_hot_encoded = encoder.fit_transform(data[categorical_features_label])

one_hot_data = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_features_label))

data_encoded = pd.concat([data, one_hot_data], axis=1)

data_encoded = data_encoded.drop(categorical_features_label, axis=1)

In [9]:
data_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 38 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   duration                      300153 non-null  float64
 1   days_left                     300153 non-null  int64
 2   price                         300153 non-null  int64
 3   airline_AirAsia               300153 non-null  float64
 4   airline_Air_India             300153 non-null  float64
 5   airline_GO_FIRST              300153 non-null  float64
 6   airline_Indigo                300153 non-null  float64
 7   airline_SpiceJet              300153 non-null  float64
 8   airline_Vistara               300153 non-null  float64
 9   source_city_Bangalore         300153 non-null  float64
 10  source_city_Chennai           300153 non-null  float64
 11  source_city_Delhi             300153 non-null  float64
 12  source_city_Hyderabad         300153 non-null  float64
 13  source_city_Kolkata           300153 non-null  float64
 14  source_city_Mumbai            300153 non-null  float64
 15  departure_time_Afternoon      300153 non-null  float64
 16  departure_time_Early_Morning  300153 non-null  float64
 17  departure_time_Evening        300153 non-null  float64
 18  departure_time_Late_Night     300153 non-null  float64
 19  departure_time_Morning        300153 non-null  float64
 20  departure_time_Night          300153 non-null  float64
 21  stops_one                     300153 non-null  float64
 22  stops_two_or_more             300153 non-null  float64
 23  stops_zero                    300153 non-null  float64
 24  arrival_time_Afternoon        300153 non-null  float64
 25  arrival_time_Early_Morning    300153 non-null  float64
 26  arrival_time_Evening          300153 non-null  float64
 27  arrival_time_Late_Night       300153 non-null  float64
 28  arrival_time_Morning          300153 non-null  float64
 29  arrival_time_Night            300153 non-null  float64
 30  destination_city_Bangalore    300153 non-null  float64
 31  destination_city_Chennai      300153 non-null  float64
 32  destination_city_Delhi        300153 non-null  float64
 33  destination_city_Hyderabad    300153 non-null  float64
 34  destination_city_Kolkata      300153 non-null  float64
 35  destination_city_Mumbai       300153 non-null  float64
 36  class_Business                300153 non-null  float64
 37  class_Economy                 300153 non-null  float64
dtypes: float64(36), int64(2)
memory usage: 87.0 MB

In [10]:
data_encoded.describe()

,duration,days_left,price,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara,source_city_Bangalore,...,arrival_time_Morning,arrival_time_Night,destination_city_Bangalore,destination_city_Chennai,destination_city_Delhi,destination_city_Hyderabad,destination_city_Kolkata,destination_city_Mumbai,class_Business,class_Economy
count,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,...,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000
mean,12.221021,26.004751,20889.660523,0.053633,0.269503,0.077204,0.143660,0.030021,0.425979,0.173448,...,0.209010,0.304971,0.170140,0.134491,0.191103,0.142347,0.165029,0.196890,0.311464,0.688536
std,7.191997,13.561004,22697.767366,0.225292,0.443702,0.266915,0.350745,0.170646,0.494491,0.378635,...,0.406602,0.460396,0.375756,0.341180,0.393170,0.349407,0.371207,0.397649,0.463093,0.463093
min,0.830000,1.000000,1105.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.830000,15.000000,4783.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,11.250000,26.000000,7425.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,16.170000,38.000000,42521.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,49.830000,49.000000,123071.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## 4. Save Cleaned Dataset (No Category) AS CSV

In [11]:
folder_name = "data"

file_name = "full_dataset_cleaned_noCategory.csv"

file_final_path = os.path.join(os.getcwd(), folder_name, file_name)

if os.path.exists(file_final_path):
    print(f"\nFile already exists. \nPlease check at the filepath: {file_final_path}\n")

else:
    data_encoded.to_csv(file_final_path, header=True, index=False)
    print(f"\nFile sucessfully saved at {file_final_path}\n")

File sucessfully saved at c:\Users\ADMIN\OneDrive\SHARED FILES\D3 Sem1\Statistical Learning\Project\data\full_dataset_cleaned_noCategory.csv